
\ we have 26 characters across and 22 down 

: PRINT-END-METAL 
    ."         GAME OVER         "
    ." Without enough FUEL to    "
    ." take off or METAL to build"
    ." new probes to collect     "
    ." more, you're stranded far "
    ." from home.                "
    ." You can only wait and hope"
    ." for a filament-thin chance"
    ." at rescue.                "
    ." Food will run out over the"
    ." coming weeks, then water, "
    ." then oxygen, after which  "
    ." your satellite will become"
    ." your coffin, as inert as  "
    ." the tomb-world below.     "
;

: PRINT-END-FUEL 
    ."         GAME OVER         "
    ." Without enough FUEL to    "
    ." take off or build new     "
    ." probes to collect more,   "
    ." you're stranded far from  "
    ." home.                     "
    ." You can only wait and hope"
    ." for a filament-thin chance"
    ." at rescue.                "
    ." Food will run out over the"
    ." coming weeks, then water, "
    ." then oxygen, after which  "
    ." your satellite will become"
    ." your coffin, as inert as  "
    ." the tomb-world below.     "
;
: PRINT-END-ART-ALL

    ."       MISSION RESULTS:    "
    ."         OUTSTANDING       "
    ."  ALL ARTIFACTS DISCOVERED "
    ."                           "
    ." Thanks to the             "
    ." comprehensive data        "
    ." collected during your     "
    ." thorough survey, given    "
    ." enough scholarly work-    "
    ." hours the MOONGRAVE case  "
    ." will one day be more or   "
    ." less open-and-shut.       "
    ." Your name will live on in "
    ." textbooks, or at least on "
    ." a wiki page somewhere--   "
    ." as close to immortality as" 
    ." a scientist can hope to   " 
    ." reach.                    "
;

: PRINT-END-ART-SOME 
    ."       MISSION RESULTS:    "
    ."           SUCCESS         "
    ."  SOME ARTIFACTS DISCOVERED"
    ."                           "
    ." The piecemeal data you    "
    ." return with breathes new  "
    ." life into the study of the"
    ." distant moon.             "
    ." The imaginations of       "
    ." academia and the public   "
    ." have been captured.       "
    ." Yours will not be the last"
    ." mission sent to MOONGRAVE."
;

: PRINT-END-ART-NONE
    ."       MISSION RESULTS:    "
    ."           FAILURE         "
    ."   NO ARTIFACTS DISCOVERED "
    ."                           "
    ." Your safe return home was "
    ." met with disappointment by" 
    ." your institution, which   "
    ." poured incalcuable        "
    ." resources into this       "
    ." expedition only for you to"
    ." return empty-handed,      "
    ." having collected no new   "
    ." data.                     "
    ." You likely won't be chosen"
    ." for a mission like this in"
    ." the future, but you are   "
    ." free to return to         "
    ." (mundane) life.           "
;